import { FormEvent, useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { api } from '../api/client';
import type { Counterparty, ExpenseDetail, Partner, Store, Tag } from '../types';
import { money } from '../utils/format';

export function ExpenseCard() {
  const { expenseId = '' } = useParams();
  const navigate = useNavigate();
  const [expense, setExpense] = useState<ExpenseDetail>();
  const [partners, setPartners] = useState<Partner[]>([]); const [counterparties, setCounterparties] = useState<Counterparty[]>([]); const [stores, setStores] = useState<Store[]>([]); const [tags, setTags] = useState<Tag[]>([]);
  const [editing, setEditing] = useState(false); const [message, setMessage] = useState('');
  const load = () => api<ExpenseDetail>(`/expenses/${expenseId}`).then(setExpense).catch((error:Error) => setMessage(error.message));
  useEffect(() => { load(); Promise.all([api<Partner[]>('/partners'),api<Counterparty[]>('/counterparties'),api<Store[]>('/stores'),api<Tag[]>('/tags')]).then(([p,c,s,t])=>{setPartners(p);setCounterparties(c);setStores(s);setTags(t);}); }, [expenseId]);
  if (!expense) return <div className="state">{message || 'Загружаем карточку…'}</div>;
  const current = expense;
  const update = (field:keyof ExpenseDetail,value:unknown) => setExpense({...current,[field]:value});
  async function save(event:FormEvent) { event.preventDefault(); await api(`/expenses/${expenseId}`,{method:'PUT',body:JSON.stringify({partner_id:current.partner_id,counterparty_id:current.counterparty_id,service_name:current.service_name,expense_month:current.expense_month,expense_year:current.expense_year,contract_number:current.contract_number||null,contract_date:current.contract_date||null,comment:current.comment||null,allocations:current.allocations.map(a=>({store_id:a.store_id,amount:a.amount||0})),tag_ids:current.tags.map(t=>t.id)})}); setEditing(false); setMessage('Изменения сохранены.'); load(); }
  async function remove() { if(window.confirm('Удалить расход?')) { await api(`/expenses/${expenseId}`,{method:'DELETE'}); navigate('/expenses'); } }
  async function addPayment(invoiceId:string) { const amount=window.prompt('Сумма платежа'); if(!amount) return; const payment_date=window.prompt('Дата платежа (ГГГГ-ММ-ДД)',new Date().toISOString().slice(0,10)); if(!payment_date) return; await api(`/invoices/${invoiceId}/payments`,{method:'POST',body:JSON.stringify({amount,payment_date})}); load(); }
  async function upload(type:'invoice'|'closing',file?:File) { if(!file)return; const body=new FormData();body.append('file',file);await api(`/expenses/${expenseId}/documents?document_type=${type}`,{method:'POST',body});load(); }
  return <><Link className="back-link" to="/expenses">← К расходам</Link><div className="page-head"><div><h1>Карточка расхода</h1><p>{message || current.service_name}</p></div><div className="head-actions"><button onClick={()=>setEditing(v=>!v)}>{editing?'Отмена':'Редактировать'}</button><button className="danger" onClick={remove}>Удалить</button></div></div>
  <form className="expense-card" onSubmit={save}><section><h2>Основные данные</h2><label>Партнер<select disabled={!editing} value={current.partner_id} onChange={e=>update('partner_id',e.target.value)}>{partners.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label>Контрагент<select disabled={!editing} value={current.counterparty_id} onChange={e=>update('counterparty_id',e.target.value)}>{counterparties.filter(x=>x.partner_id===current.partner_id).map(x=><option value={x.id} key={x.id}>{x.full_name}</option>)}</select></label><label>Услуга<input disabled={!editing} value={current.service_name} onChange={e=>update('service_name',e.target.value)}/></label><div className="row"><label>Месяц<input disabled={!editing} type="number" value={current.expense_month} onChange={e=>update('expense_month',Number(e.target.value))}/></label><label>Год<input disabled={!editing} type="number" value={current.expense_year} onChange={e=>update('expense_year',Number(e.target.value))}/></label></div><label>Комментарий<textarea disabled={!editing} value={current.comment||''} onChange={e=>update('comment',e.target.value)}/></label>{editing&&<button className="primary">Сохранить</button>}</section>
  <section><h2>Магазины и теги</h2><label>Магазины<select disabled={!editing} multiple value={current.allocations.map(a=>a.store_id)} onChange={e=>update('allocations',Array.from(e.target.selectedOptions).map(o=>({store_id:o.value,store:o.text,amount:'0'})))}>{stores.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label>Теги<select disabled={!editing} multiple value={current.tags.map(t=>t.id)} onChange={e=>update('tags',Array.from(e.target.selectedOptions).map(o=>({id:o.value,name:o.text})))}>{tags.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label></section>
  <section className="card-wide"><h2>Счета и платежи</h2>{current.invoices.length?current.invoices.map(i=><article className="invoice-card" key={i.id}><div><b>Счет № {i.invoice_number}</b><span>{i.invoice_date} · {money(i.amount)}</span></div><button type="button" onClick={()=>addPayment(i.id)}>+ Добавить платеж</button>{i.payments.map(p=><small key={p.id}>{p.payment_date}: {money(p.amount)}</small>)}</article>):<p>Счетов пока нет.</p>}</section>
  <section className="card-wide"><h2>Документы</h2><div className="upload-actions"><label className="file-button">Загрузить счет<input hidden type="file" accept=".pdf,.jpg,.jpeg,.png" onChange={e=>upload('invoice',e.target.files?.[0])}/></label><label className="file-button">Загрузить закрывающий документ<input hidden type="file" accept=".pdf,.jpg,.jpeg,.png" onChange={e=>upload('closing',e.target.files?.[0])}/></label></div>{current.documents.map(d=><p key={d.id}>{d.document_type==='invoice'?'Счет':'Закрывающий документ'}: {d.original_filename}</p>)}</section></form></>;
}
