import { useEffect,useState } from 'react';
import { api } from '../api/client';
import type { RecognitionJournalItem } from '../types';
import { copyText } from '../utils/clipboard';

type Detail=RecognitionJournalItem&{primary_fields:Record<string,{value?:string}>;ai_fields:Record<string,{value?:string}>;final_fields:Record<string,{value?:string}>;prompt:string};
const statusLabels:Record<string,string>={new:'Новая',prompt_copied:'Промт скопирован',in_progress:'В работе',fixed:'Исправлено',no_fix_required:'Не требует исправления'};
const fieldLabels:Record<string,string>={partner:'Партнер',counterparty:'Контрагент',service_name:'Услуга / товар',invoice_number:'№ счета',invoice_date:'Дата счета',amount:'Сумма счета'};
export function RecognitionJournal(){const [items,setItems]=useState<RecognitionJournalItem[]>([]);const [summary,setSummary]=useState<{field:string;label:string;count:number}[]>([]);const [field,setField]=useState('');const [status,setStatus]=useState('');const [result,setResult]=useState('');const [dateFrom,setDateFrom]=useState('');const [dateTo,setDateTo]=useState('');const [detail,setDetail]=useState<Detail|null>(null);const [message,setMessage]=useState('');
  async function load(){const query=new URLSearchParams();if(field)query.set('problem_field',field);if(status)query.set('status',status);if(result)query.set('result',result);if(dateFrom)query.set('date_from',dateFrom);if(dateTo)query.set('date_to',dateTo);try{const x=await api<{items:RecognitionJournalItem[];summary:{field:string;label:string;count:number}[]}>(`/recognition-journal?${query}`);setItems(x.items);setSummary(x.summary);}catch(e){setMessage(e instanceof Error?e.message:'Не удалось загрузить журнал');}}
  useEffect(()=>{load();},[field,status,result,dateFrom,dateTo]);
  async function open(id:string){setDetail(await api<Detail>(`/recognition-journal/${id}`));}
  async function updateStatus(value:string){if(!detail)return;await api(`/recognition-journal/${detail.id}/status`,{method:'PUT',body:JSON.stringify({status:value})});setDetail({...detail,status:value});load();}
  async function copyPrompt(){if(!detail)return;await copyText(detail.prompt);await updateStatus('prompt_copied');setMessage('Промт скопирован');}
  const show=(fields:Record<string,{value?:string}>,key:string)=>fields[key]?.value||'НЕ РАСПОЗНАНО';
  return <><div className="page-head"><div><h1>Журнал распознавания</h1><p>Случаи, когда основному механизму потребовался AI fallback</p></div></div>
    <section className="journal-summary">{summary.map(x=><article key={x.field}><span>{x.label}</span><b>{x.count}</b><small>за 30 дней</small></article>)}</section>
    <div className="toolbar-panel journal-filters"><label>С даты<input type="date" value={dateFrom} onChange={e=>setDateFrom(e.target.value)}/></label><label>По дату<input type="date" value={dateTo} onChange={e=>setDateTo(e.target.value)}/></label><label>Проблемное поле<select value={field} onChange={e=>setField(e.target.value)}><option value="">Все</option>{Object.entries(fieldLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Результат<select value={result} onChange={e=>setResult(e.target.value)}><option value="">Все</option><option value="success">6/6</option><option value="partial">Частично</option><option value="error">Ошибка API</option></select></label><label>Статус<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Все</option>{Object.entries(statusLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label></div>
    {message&&<div className="notice">{message}</div>}<div className="table-wrap"><table><thead><tr><th>Дата</th><th>Счет</th><th>Контрагент</th><th>Проблема</th><th>Результат</th><th>Статус</th><th></th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td>{new Date(x.created_at).toLocaleString('ru-RU')}</td><td>{x.invoice_number||'—'} от {x.invoice_date||'—'}</td><td>{x.counterparty||'—'}</td><td>{x.missing_labels.join(', ')}</td><td>{x.success?'6/6':x.error?'Ошибка':'Частично'}</td><td>{statusLabels[x.status]||x.status}</td><td><button onClick={()=>open(x.id)}>Открыть</button></td></tr>)}</tbody></table></div>
    {detail&&<div className="overlay"><section className="document-preview journal-detail"><button className="close" onClick={()=>setDetail(null)}>×</button><h2>Счет №{detail.invoice_number||'—'} от {detail.invoice_date||'—'}</h2><label>Статус<select value={detail.status} onChange={e=>updateStatus(e.target.value)}>{Object.entries(statusLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><div className="recognition-compare"><section><h3>Основное распознавание</h3>{Object.keys(fieldLabels).map(k=><p key={k}><b>{fieldLabels[k]}:</b> {show(detail.primary_fields,k)}</p>)}</section><section><h3>Результат AI</h3>{detail.missing_fields.map(k=><p key={k}><b>{fieldLabels[k]}:</b> {show(detail.ai_fields,k)}</p>)}</section><section><h3>Итог пользователя</h3>{detail.missing_fields.map(k=><p key={k}><b>{fieldLabels[k]}:</b> {show(detail.final_fields,k)}</p>)}</section></div><h3>Промт для Codex</h3><pre>{detail.prompt}</pre><button className="primary" onClick={copyPrompt}>Скопировать промт</button></section></div>}
  </>}
